package {{ .PackageName }}

type ApiGroup struct {
	// Code generated by github.com/lzsgo/lzs-go-admin/server Begin; DO NOT EDIT.

	// Code generated by github.com/lzsgo/lzs-go-admin/server End; DO NOT EDIT.
}
